name: üöÄ PIZZa-Frog Release
on:
  pull_request:
    branches: [ main ]
    types: [closed]
  workflow_dispatch:
permissions:
  contents: write    # Required to push version bump commits
  id-token: write
  actions: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged == true
    steps:
    - name: üì• Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main
        fetch-depth: 0
        
    #########################################################
    #################### Injected By Fly ####################

    - name: üê∏ JFrog Fly - Set as Default Registry for All Package Managers
      uses: jfrog/fly-action@v1
      with:
        url: https://naftalig1011.jfrog.info
        ignore: mvn, maven

    #################### Injected By Fly ####################
    #########################################################


    - name: üê≥ Docker Build and Push - pizza-back
      shell: bash
      run: |
        VERSION=$(date +"%Y.%m.%d-%H.%M.%S")
        REGISTRY="naftalig1011.jfrog.info"
        IMAGE_NAME="$REGISTRY/docker/pizza-app-test:$VERSION"
        echo "üì¶ Building Docker version: $VERSION"
        echo "üåê Using registry: $REGISTRY"
        echo "üè∑Ô∏è Image name: $IMAGE_NAME"
        
        # Build the Docker image
        docker build \
          --build-arg FLY_REGISTRY_DOMAIN="$REGISTRY" \
          -t "$IMAGE_NAME" \
          .
        
        # Push
        docker push "$IMAGE_NAME"
        
        echo "‚úÖ Docker image pushed successfully"
        touch .fly-job-status
